services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: cs25
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  chroma:
    image: ghcr.io/chroma-core/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - chroma-data:/data

#  spring-app:
#    build: .
#    ports:
#      - "8080:8080"
#    restart: always
#    depends_on:
#      - mysql
#      - redis
#    env_file:
#      - .env

volumes:
  mysql-data:
  redis-data:
  chroma-data:
