version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: cs25

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    # 비밀번호 설정 제거
    command: [ "redis-server", "--appendonly", "yes" ]
