version: '3.8'
services:
  cs25-mysql:
    image: mysql:8.0.35

    platform: linux/amd64
    volumes:
      - cs25_mysql_volume:/var/lib/mysql
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: k8722@2714
      MYSQL_DATABASE: cs25
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]

  cs25-redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    volumes:
      - cs25_redis_volume:/data
    command: redis-server --requirepass redispassword --appendonly yes

volumes:
  cs25_mysql_volume:
  cs25_redis_volume:

# mysql 만 일단 추가해놨고 나중에 배포에 피룡한 CI/CD 생기면 그때 추가하던지...