global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'cs25-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cs25-service:8080' ]

  - job_name: 'cs25-batch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cs25-batch:8080' ]