package com.example.cs25.domain.userQuizAnswer.entity;

import com.example.cs25.domain.quiz.entity.Quiz;
import com.example.cs25.domain.users.entity.User;
import com.example.cs25.global.entity.BaseEntity;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@Entity
@Table(name = "userQuizAnswers")
@NoArgsConstructor
public class UserQuizAnswer extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String userAnswer;
    private String aiFeedback;
    private Boolean isCorrect;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_id")
    private Quiz quiz;

    /**
     * Constructs a UserQuizAnswer entity with the specified properties.
     *
     * @param userAnswer the user's answer text
     * @param aiFeedback feedback generated by AI for the answer
     * @param isCorrect  correctness status of the answer
     * @param user       the user who submitted the answer
     * @param quiz       the quiz to which this answer belongs
     */
    @Builder
    public UserQuizAnswer(String userAnswer, String aiFeedback, Boolean isCorrect, User user,
        Quiz quiz) {
        this.userAnswer = userAnswer;
        this.aiFeedback = aiFeedback;
        this.isCorrect = isCorrect;
        this.user = user;
        this.quiz = quiz;
    }
}
