name: Deploy CS25 Batch to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'cs25-batch/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_BATCH_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BATCH_TOKEN }}

      - name: Build and push cs25-batch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cs25-batch/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_BATCH_USERNAME }}/cs25-batch:latest
            ${{ secrets.DOCKERHUB_BATCH_USERNAME }}/cs25-batch:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo "Image pushed successfully with tags latest and ${{ github.sha }}"