name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feat/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo yum update -y && sudo yum install -y java-17-amazon-corretto
            # 기존 java -jar 프로세스 모두 강제 종료
            for pid in $(pgrep java); do
              if ps -p $pid -o args= | grep -q 'java -jar'; then
                echo "Terminating Java process (PID: $pid)"
                kill -9 $pid
              fi
            done
            
            export MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export KAKAO_ID=${{ secrets.KAKAO_ID }}
            export KAKAO_SECRET=${{ secrets.KAKAO_SECRET }}
            export REDIS_PASSWORD=

            # 애플리케이션 즉시 재기동 (백그라운드)
            nohup java -jar /home/ec2-user/cs25-0.0.1-SNAPSHOT.jar \
              --spring.profiles.active=local \
              > /home/ec2-user/app.log 2>&1 &
